name: Coverage
on:
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
      - name: Install node modules
        run: npm install
      - name: Test code
        run: npm test
      - name: Send coverage info to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}